---
# Jellyfin Plugin Metadata
name: "TheSportsDB"
guid: "55d3efd0-c081-4e0b-a57a-09402a4d549d"
version: "1.3.6.0"
targetAbi: "10.9.0.0"
framework: "net8.0"
overview: "Formula 1 metadata provider using TheSportsDB API"
description: >
  Provides Formula 1 metadata for seasons, races, teams, and drivers
  using TheSportsDB.com API. Supports organizing F1 race recordings
  with detailed metadata including race results, team information,
  and driver data.
category: "Metadata"
owner: "sindrej"
artifacts:
- "Jellyfin.Plugin.TheSportsDB.dll"
changelog: >
  Fixed heredoc syntax in release workflow to properly create GitHub releases
