---
# Jellyfin Plugin Metadata
name: "TheSportsDB"
guid: "55d3efd0-c081-4e0b-a57a-09402a4d549d"
version: "1.4.1.0"
targetAbi: "10.9.0.0"
framework: "net8.0"
overview: "Metadata provider using TheSportsDB API"
description: >
  Provides sports metadata using TheSportsDB.com API.
category: "Metadata"
owner: "sindrej"
artifacts:
- "Jellyfin.Plugin.Tsdb.dll"
changelog: >
  Fixed heredoc syntax in release workflow to properly create GitHub releases
